@startuml
!include ../domainStory.puml

Boundary(office) {
    Group(people)
    Call(conference)
    activity(6, (people), attend, (conference))
}

note top of office : above?
note right of office : right
note bottom of office : below?
note left of office : left

Boundary(one, $note= default) {
    Person(Jake)
}
Boundary(two, $note=^ above) {
    Person(Simon)
}
Boundary(three, $note=> right) {
    Person(Sloane)
}
Boundary(four, $note=v below) {
    Person(Marry)
}
Boundary(five, $note=< left) {
    Person(Ashley)
}
@enduml
