@startuml
!$textColor = "white"
!$actorColor = "green"
!$stepColor = "#c8d3f5"
!$stepFontColor = "#212337"
!$noteColor = "#3f3f3f"
!$actorStyle = "material"

!include ../domainStory.puml

skinparam backgroundColor #111111
skinparam dpi 80


!unquoted procedure compose($predicate, $object, $post = "", $target = "", $objectArr = "", $targetArr = "", $color = "", $scale = "", $note = "")
    !$start = $lastObjectName

    ' ensure the object exists / create one dynamically
    !$object = $ensureObjectExists($object, $color, $scale)

    !if $objectArr == ""
        !$objectArr = "-->"
    !endif

    ' create connecting arrows
    $arrow($start, $object, $objectArr) : $predicate

    !if $targetArr == ""
        !$targetArr = $objectArr
    !endif

    !if $post != "" && $post != "_"
        !if $target != "" && $target != "_"
            $arrow($object, $target, $targetArr) : $post
        !else
            $arrow($object, $post, $targetArr)
        !endif
    !endif

    $addNote($object, $note)
!endprocedure

Person(A)
Person(B)
Person(B2, $label="B")
Person(B3, $label="B")
Person(C)
Person(A2, $label="A")
Person(A3, $label="A")
Person(A4, $label="A")
Person(A5, $label="A")
Document(w, $color="white")
Document(w2, $label="w", $color="white")
Document(w3, $label="w", $color="white")
Document(w4, $label="w", $color="white")
Document(w5, $label="w", $color="white")
Document(v, $color="white")

activity(_, A, works on, w)
activity(_, A2, works on, w2, using, v)
activity(_, A3, hands over, w3, to, B)
activity(_, A4, hands over, w4, to, B2)
compose(and, C)
activity(_, A5, collaborates on, w5)
activity(|, B3, collaborates on, w5, $objectArr = "<--")

@enduml
