@startuml
!include ../domainStory.puml

Person(pete)

note top of pete : above
note right of pete : right
note bottom of pete : below
note left of pete : left

Email(confirmation, $note= default)
System(boarding, $note=^ above)
Document(list, $note=> right)
Folder(documents, $note=v below)
Call(question, $note=< left)

Person(person)

activity(1, person, reads, thing1, $note=  default)
activity(2, person, reads, thing4, $note=^ above)
activity(3, person, reads, thing5, $note=> right)
activity(4, person, reads, thing2, $note=v below)
activity(5, person, reads, thing3, $note=< left)
@enduml
