@startuml

!$storyLayout = topToBottom
!$textColor = Navy
!$actorColor = RoyalBlue
!$objectColor = RoyalBlue
!$stepColor = PowderBlue

!include ../domainStory.puml

Boundary(Party) {
    Person(Alice)
    Conversation(weather)
    Person(Bob)
}

activity(1, Alice, talks about the, weather, with, Bob)
@enduml
