@startuml
!theme bluegray

!include ../../../src/domainStoryComposite.puml

Boundary(Party) {
    introduce(Person(Alice))
    introduce(Conversation(weather))
    introduce(Person(Bob))
}

activity(1, Alice, talks about the, weather, with, Bob)
@enduml
