@startuml
!theme reddress-darkgreen
!$THEME='reddress-darkgreen'

skinparam Agent {
    accent_style()
    font_style()
}

skinparam Card {
    light_style()
    font_style()
}

!$Story_Layout = 'top-to-bottom'
!$Step_FontColor = '#113300'
!$Step_BackgroundColor = '#228811'

!include ../../../src/domainStoryComposite.puml

Boundary(Party) {
    Person(Alice)
    Conversation(weather)
    Person(Bob)
}

activity(1, Alice, talks about the, weather, with, Bob)
@enduml
