@startuml
!pragma layout smetana

!includesub ../../../../puml/notes/boundaries-leftToRight-library.IGNORE.puml!setUp
!includesub ../../../../puml/notes/boundaries-leftToRight-library.IGNORE.puml!inverse
@enduml
