@startuml
!$storyLayout = 'top-to-bottom'

!include ../../domainStory.puml

Boundary(office) {
    Group(people)
    Call(conference)
    activity(6, (people), attend, (conference))
}

note bottom of office : below?
note left of office : left
note right of office : right
note top of office : above?

Boundary(one, $note= default) {
    Person(Jake)
}
Boundary(two, $note=^ above) {
    Person(Simon)
}
Boundary(three, $note=> right) {
    Person(Sloane)
}
Boundary(four, $note=v below) {
    Person(Marry)
}
Boundary(five, $note=< left) {
    Person(Ashley)
}
Boundary(six, $note=~ inverse) {
    Person(Sam)
}

@enduml
