@startuml
!$Story_Layout = 'top-to-bottom'

!include ../../src/domainStoryComposite.puml

Person(pete)

note top of pete : above
note right of pete : right
note bottom of pete : below
note left of pete : left

Email(confirmation, $note= default)
Info(news, $note=^ above)
Document(list, $note=> right)
Folder(documents, $note=v below)
Call(question, $note=< left)
Conversation(argument, $note=~ inverse)

Person(Alice, $note= default)
Group(Employees, $note=~ inverse)
System(Boarding, $note=^ above)

Person(person)

Info(thing1)
Info(thing2)
Info(thing3)

activity(1, person, reads, thing1, $note= default)
activity(2, person, reads, thing2, $note=^ above)
activity(3, person, reads, thing3, $note=> right)
activity(4, person, reads, Info: thing4, $note=v below)
activity(5, person, reads, Info: thing5, $note=~ inverse)
activity(6, person, reads, Info: thing6, $note=> right)
activity(7, person, reads, Document:Book, $note=< left)
@enduml
