@startuml
!$Story_Layout = 'top-to-bottom'

!include ../../../src/domainStoryComposite.puml

introduce(Person(colleague1))
introduce(Conversation(defaultMovie))
introduce(Person(colleague2))
introduce(Conversation(rightMovie))
introduce(Person(colleague3))
introduce(Conversation(leftMovie))
introduce(Person(colleague4))
introduce(Conversation(downMovie))
introduce(Person(colleague5))
introduce(Conversation(upMovie))
introduce(Person(colleague6))
introduce(Conversation(reverseMovie))
introduce(Person(colleague7))

activity(1, colleague1, talks about, defaultMovie, with, colleague2)
activity(^2, colleague1, talks about, upMovie, with, colleague3)
activity(>3, colleague1, talks about, rightMovie, with, colleague4)
activity(v4, colleague1, talks about, downMovie, with, colleague5)
activity(<5, colleague1, talks about, leftMovie, with, colleague6)
activity(~6, colleague1, talks about, reverseMovie, with, colleague7)
@enduml
