@startebnf
styleProperties =
"Default", defaultProperties |\
actors, [?TAG_NAME?], elementProperties |\
workObjects, [?TAG_NAME?], elementProperties |\
"Boundary", [?TAG_NAME?], boundaryProperties |\
"Note", defaultProperties |\
"Activity", activityProperties |\
"Step", stepProperties;

actors = "Actor" | "Person" | "Group" | "System";
workObjects = "Object" | "Document" | "Folder" | "Call" | "Email" | "Conversation" | "Info";

defaultProperties = "FontColor" | "FontName" | "FontSize" | "FontStyle" | "TextAlignment" | "BackgroundColor" | "BorderStyle" | "BorderColor" | "BorderThickness" | "RoundCorner" | "Shadowing";
elementProperties = "Shape" | "IconStyle" | "IconScale" | "IconColor" | defaultProperties;
boundaryProperties = "Shape" | defaultProperties;

activityProperties = "Shape" | "FontColor" | "FontName" | "FontSize" | "FontStyle" | "MessageAlignment" | "Color";
stepProperties = "FontColor" | "FontSize" | "BackgroundColor";

@endyaml
