@startmindmap
top to bottom direction

title Style declarations

* Style Declarations
** Default
*** Actor
**** Person
***** PersonTAG_NAME
**** Group
***** GroupTAG_NAME
**** System
***** SystemTAG_NAME
**** ActorTAG_NAME
*** Object
**** Document
***** DocumentTAG_NAME
**** Folder
***** FolderTAG_NAME
**** Call
***** CallTAG_NAME
**** Email
***** EmailTAG_NAME
**** Conversation
***** ConversationTAG_NAME
**** Info
***** InfoTAG_NAME
**** ObjectTAG_NAME
*** Note
*** Boundary
**** BoundaryTAG_NAME
** Activity
'*** ActivityTAG_NAME
** Step
@endmindmap
