@startuml
!include ../../src/domainStoryComposite.puml

Person(superior)
Document(document1)
Person(subordinate1)
Document(document2)
Person(subordinate2)
Document(document3)
Person(subordinate3)
Document(document4)
Person(subordinate4)
Document(document5)
Person(subordinate5)
Document(document6)
Person(subordinate6)
'Document(document7)
'Person(subordinate7)
'Document(document8)
'Person(subordinate8)

activity(_, superior, talks about, document1, with, subordinate1, -->, -->)
activity(_, superior, talks about, document2, with, subordinate2, -->, <-)
activity(_, superior, talks about, document3, with, subordinate3, -->, ->)

activity(_, superior, talks about, document4, with, subordinate4, <--, <--)
activity(_, superior, talks about, document5, with, subordinate5, <--, <-)
activity(_, superior, talks about, document6, with, subordinate6, <--, ->)

'activity(_, superior, talks about, document7, with, subordinate3, -->, <--)
'activity(_, superior, talks about, document8, with, subordinate5, <--, -->)
@enduml
