@startuml
!include ../../domainStory.puml

Person(superior)
Document(document1)
Person(subordinate1, EE)
Document(document2)
Person(subordinate2)
'Document(document3)
'Person(subordinate3)
Document(document4)
Person(subordinate4)
'Document(document5)
'Person(subordinate5)
Document(document6)
Person(subordinate6)
Document(document7)
Person(subordinate7)
Document(document8)
Person(subordinate8)

activity(_, superior, talks about, document1, with, subordinate1, -->, -->)
activity(_, superior, talks about, document2, with, subordinate2, -->, ->)
activity(_, superior, talks about, document4, with, subordinate4, -->, <-)
'activity(_, superior, talks about, document3, with, subordinate3, -->, <--)
'activity(_, superior, talks about, document5, with, subordinate5, <--, -->)
activity(_, superior, talks about, document6, with, subordinate6, <--, ->)
activity(_, superior, talks about, document7, with, subordinate7, <--, <--)
activity(_, superior, talks about, document8, with, subordinate8, <--, <-)

Person(customer)
Conversation(topic1)
Person(cashier1)
Conversation(topic2)
Person(cashier2)
Conversation(topic3)
Person(cashier3)
'Conversation(topic4)
'Person(cashier4)
Conversation(topic5)
Person(cashier5)
'Conversation(topic6)
'Person(cashier6)
Conversation(topic7)
Person(cashier7)
Conversation(topic8)
Person(cashier8)

activity(_, customer, talks about, topic1, with, cashier1, ->, -->)
activity(_, customer, talks about, topic2, with, cashier2, ->, ->)
activity(_, customer, talks about, topic3, with, cashier3, ->, <--)
'activity(_, customer, talks about, topic4, with, cashier4, ->, <-)
activity(_, customer, talks about, topic5, with, cashier5, <-, -->)
'activity(_, customer, talks about, topic6, with, cashier6, <-, ->)
activity(_, customer, talks about, topic7, with, cashier7, <-, <--)
activity(_, customer, talks about, topic8, with, cashier8, <-, <-)

@enduml
