@startuml
!include ../../src/domainStoryComposite.puml

Person(Alice)
Person(Bob)
Info(weather)

activity(_, Alice, talks about the, weather,    , Bob, <--, <--)
activity(_, Alice, talks about the, weather,   _, Bob, <--, <--)
activity(_, Alice, talks about the, weather, Bob,    , <--)
activity(_, Alice, talks about the, weather, Bob,   _, <--)
activity(_, Alice, talks about the, weather,   _,   _, <--)
activity(_, Alice, talks about the, weather,    ,    , <--)
@enduml
