@startuml
!include ../../domainStory.puml

Person(Bob)
Person(Alice)

Info(weather1, weather)
Info(weather2, good weather)
Info(weather3, bad weather)
Info(weather4, mixed weather)
Conversation(talking1, talking)
Conversation(talking2, the exaggerated talk)
Conversation(talking3, talking)
Email(mail, an exasperated e-mail)

activity(_, Bob, talks about the, weather1) /' auto-increment will create step 1 '/
activity(+, Bob, talks about the, weather2) /' auto-increment will create step 2 '/
activity(|, Alice, talks about the, weather2) /' no increment will create step 2 '/
' will not create step, nor auto-increment, and will not display the step label
activity(<., Bob, also talks about the, weather3)
activity(42, Alice, asks about all the, talking1, again, Bob) /' will create step 42 '/
activity(|, Bob, talks about the, weather4) /' no increment will still create step 2 '/
' will create step 10 and set the step counter to 10
activity(=10, Alice, talks about, talking2, Bob)
activity(<_, Bob, is embarrassed about, talking3) /' auto-increment will create step 11 '/
' will not create step, nor auto-increment, and will not display the step label
activity( , Alice, writes, mail, to, Bob)
@enduml
