@startmindmap
top to bottom direction

title Style declarations

* Style Declarations
** Default
*** Actor
**** Person
**** Group
**** System
*** Object
**** Document
**** Folder
**** Call
**** Email
**** Conversation
**** Info
*** Note
*** Boundary
** Activity
** Step
@endmindmap
