' Actors
' ##################################

' Person Actor
' ==================================

!global $Person_IconStyle ?= $Actor_IconStyle

!if $Person_IconStyle == "stickman"
    !$Person_Shape ?= "Actor"
    $extendStyleDeclarations("Actor", "Person", "")
    skinparam ActorStyle stickman
!elseif $Person_IconStyle == "stickmanAlt"
    !$Person_Shape ?= "Actor/"
    $extendStyleDeclarations("Actor", "Person", "")
    skinparam ActorStyle stickman
!elseif $Person_IconStyle == "hollow"
    !$Person_Shape ?= "Actor"
    $extendStyleDeclarations("Actor", "Person", "")
    skinparam ActorStyle hollow
!elseif $Person_IconStyle == "awesome"
    !$Person_Shape ?= "Actor"
    $extendStyleDeclarations("Actor", "Person", "")
    skinparam ActorStyle awesome
!elseif $Person_IconStyle == "outline"
    $extendStyleDeclarations("Actor", "Person", "account_outline")
!else
    $extendStyleDeclarations("Actor", "Person", "account")
!endif

!unquoted function Person($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Actor("Person", $Person_IconName, $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

' Group Actor
' ==================================

!global $Group_IconStyle ?= $Actor_IconStyle

!if $Group_IconStyle == "outline"
    $extendStyleDeclarations("Actor", "Group", "account_multiple_outline")
!else
    $extendStyleDeclarations("Actor", "Group", "account_multiple")
!endif

!unquoted function Group($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Actor("Group", $Group_IconName, $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

' System Actor
' ==================================

$extendStyleDeclarations("Actor", "System", "laptop")

!unquoted function System($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Actor("System", $System_IconName, $name, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction
