' Entity Creation
' ##################################

!unquoted function Actor($kind, $icon, $name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $DST_PUML_ENTITY_NAMES == "static"
        !$actorName = $createElement("Actor", $kind, $icon, $name, $label, $tag, $shape, $scale, $color, $background)
        $createElementNote($name, $note)
    !else
        !$tmpLabel = $name
        !$name = $computeNextElementName("Actor")
        !$actorName = $createElement("Actor", $kind, $icon, $name, $tmpLabel, $label, $note, $shape, $scale, $color)
        $createElementNote($name, $tag)
    !endif

    !return $actorName
!endfunction

!unquoted function Object($kind, $icon, $name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $DST_PUML_ENTITY_NAMES == "static"
        !$objectName = $createElement("Object", $kind, $icon, $name, $label, $tag, $shape, $scale, $color, $background)
        $createElementNote($name, $note)
    !else
        !$tmpLabel = $name
        !$name = $computeNextElementName("Object")
        !$objectName = $createElement("Object", $kind, $icon, $name, $tmpLabel, $label, $note, $shape, $scale, $color)
        $createElementNote($name, $tag)
    !endif

    !return $objectName
!endfunction

!unquoted function $createElement($type, $kind, $icon, $name, $label = "", $tag = "", $shape = "", $scale = "", $color = "", $background = "")
    $debug($type + "(" + $kind + ", " + $icon + ") " + $name + " : " + $label + " : " + $tag + " : " + $shape + " : " + $scale + " : " + $color + " : " + $background)

    !if $label == ""
        !$label = $name
    !endif

    !$shape = $getStyleProperty($shape, $type, $kind, $tag, Shape)
    !$scale = $getStyleProperty($scale, $type, $kind, $tag, IconScale)
    !$color = $getStyleProperty($color, $type, $kind, $tag, IconColor)

    !$backgroundColor = $computeColorName($background)
    !$stereotypes = $computeStereotypes($kind, $tag)

    ' output below
    $pumlEntity($shape, $label, $name, $icon, $scale, $color, $stereotypes, $backgroundColor)

    !if $activityContext == "open"
        !return $name
    !else
        !return ""
    !endif
!endfunction

!function $computeNextElementName($type)
    !$prefix = %lower($type)
    !$counterName = "$" + $prefix + "Counter"

    !$nextValue = %get_variable_value($counterName) + 1
    %set_variable_value($counterName, $nextValue)

    !return $prefix + %string($nextValue)
!endfunction
