'' DomainStory-PlantUML
''
'' Use PlantUML to describe and document a domain story which was developed in a
'' Domain Storytelling workshop.
''
'' Author: Johannes Thorn
'' Version: 0.4.0
'' Source: https://github.com/johthor/DomainStory-PlantUML
''
