' Helper functions
' ##################################

!function $computeColorName($colorSpec)
    !if $colorSpec
        !$hexColor = %substr($colorSpec, 0, 1)
        !if $hexColor == "#"
            !return $colorSpec
        !else
            !return "#" + $colorSpec
        !endif
    !else
        !return ""
    !endif
!endfunction

!function $computeArrowDirection($step)
    !$activityDirection = %substr($step, 0, 1)
    !if $activityDirection == "^"
        !if $Story_Layout == "left-to-right"
            !return "<-"
        !else
            !return "<--"
        !endif
    !elseif $activityDirection == ">"
        !if $Story_Layout == "left-to-right"
            !return "-->"
        !else
            !return "->"
        !endif
    !elseif $activityDirection == "<"
        !if $Story_Layout == "left-to-right"
            !return "<--"
        !else
            !return "<-"
        !endif
    !elseif  $activityDirection == "v"
        !if $Story_Layout == "left-to-right"
            !return "->"
        !else
            !return "-->"
        !endif
    !elseif  $activityDirection == "~"
        !return "<--"
    !else
        ' Signal no direction found
        !return %false()
    !endif
!endfunction

!function $computeStepLabel($step)
    !$stepNumber = $computeStepNumber($step)

    !if $stepNumber
        !if $Step_LabelFraming == "round"
            !$result = "(" + $stepNumber + ")"
        !elseif $Step_LabelFraming == "square"
            !$result = "[" + $stepNumber + "]"
        !elseif $Step_LabelFraming == "curly"
            !$result = "{" + $stepNumber + "}"
        !elseif $Step_LabelFraming == "pointy"
            !$result = "〈" + $stepNumber + "〉"
        !else
            !$result = $stepNumber
        !endif

        !if $Step_FontStyle == "bold"
            !$result = "**" + $result + "**"
        !elseif $Step_FontStyle == "italic"
            !$result = "//" + $result + "//"
        !elseif $Step_FontStyle == "monospace"
            !$result = '""' + $result + '""'
        !elseif $Step_FontStyle == "underline"
            !$result = "__" + $result + "__"
        !elseif $Step_FontStyle == "wave"
            !$result = "~~" + $result + "~~"
        !endif

        !if $Step_FontColor
            !$result = "<color:" + $Step_FontColor + ">" + $result + "</color>"
        !endif
        !if $Step_FontSize
            !$result = "<size:" + $Step_FontSize + ">" + $result + "</size>"
        !endif
        !if $Step_BackgroundColor
            !$result = "<back:" + $Step_BackgroundColor + ">" + $result + "</back>"
        !endif
        !return $result
    !else
        !return ""
    !endif
!endfunction

!function $computeStepNumber($step)
    !if $step == "_" || $step == "+"
        !$stepCounter = $stepCounter + 1
        !return $stepCounter
    !elseif $step == "|"
        !if $stepCounter
            !return $stepCounter
        !else
            !return '?'
        !endif
    !elseif %substr($step, 0, 1) == "="
        !$stepCounter = %intval(%substr($step, 1))
        !return $stepCounter
    !elseif $step == "."
        ' Signal unnumbered step
        !return %false()
    !else
        !return $step
    !endif
!endfunction
