' Work Objects
' ##################################

' Document Work Object
' ==================================

!global $Document_IconStyle ?= $Object_IconStyle

!if $Document_IconStyle == "outline"
    $extendStyleDeclarations("Object", "Document", "file_document")
!else
    $extendStyleDeclarations("Object", "Document", "document")
!endif

!unquoted function Document($label, $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Object("Document", $Document_IconName, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

!unquoted procedure namedDocument($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $label == ""
        !$label = $name
    !endif
    introduce($name, Document($label, $tag, $note, $shape, $scale, $color, $background))
!endprocedure

' Folder Work Object
' ==================================

!global $Folder_IconStyle ?= $Object_IconStyle

!if $Folder_IconStyle == "outline"
    $extendStyleDeclarations("Object", "Folder", "folder_outline")
!else
    $extendStyleDeclarations("Object", "Folder", "folder")
!endif

!unquoted function Folder($label, $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Object("Folder", $Folder_IconName, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

!unquoted procedure namedFolder($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $label == ""
        !$label = $name
    !endif
    introduce($name, Folder($label, $tag, $note, $shape, $scale, $color, $background))
!endprocedure

' Call Work Object
' ==================================

$extendStyleDeclarations("Object", "Call", "phone")

!unquoted function Call($label, $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Object("Call", $Call_IconName, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

!unquoted procedure namedCall($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $label == ""
        !$label = $name
    !endif
    introduce($name, Call($label, $tag, $note, $shape, $scale, $color, $background))
!endprocedure

' Email Work Object
' ==================================

!global $Email_IconStyle ?= $Object_IconStyle

!if $Email_IconStyle == "outline"
    $extendStyleDeclarations("Object", "Email", "at")
!else
    $extendStyleDeclarations("Object", "Email", "email")
!endif

!unquoted function Email($label, $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Object("Email", $Email_IconName, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

!unquoted procedure namedEmail($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $label == ""
        !$label = $name
    !endif
    introduce($name, Email($label, $tag, $note, $shape, $scale, $color, $background))
!endprocedure

' Conversation Work Object
' ==================================

!global $Conversation_IconStyle ?= $Object_IconStyle

!if $Conversation_IconStyle == "outline"
    $extendStyleDeclarations("Object", "Conversation", "message_outline")
!else
    $extendStyleDeclarations("Object", "Conversation", "message")
!endif

!unquoted function Conversation($label, $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Object("Conversation", $Conversation_IconName, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

!unquoted procedure namedConversation($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $label == ""
        !$label = $name
    !endif
    introduce($name, Conversation($label, $tag, $note, $shape, $scale, $color, $background))
!endprocedure

' Info Work Object
' ==================================

!global $Info_IconStyle ?= $Object_IconStyle

!if $Info_IconStyle == "outline"
    $extendStyleDeclarations("Object", "Info", "information_outline")
!else
    $extendStyleDeclarations("Object", "Info", "information")
!endif

!unquoted function Info($label, $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !return Object("Info", $Info_IconName, $label, $tag, $note, $shape, $scale, $color, $background)
!endfunction

!unquoted procedure namedInfo($name, $label = "", $tag = "", $note = "", $shape = "", $scale = "", $color = "", $background = "")
    !if $label == ""
        !$label = $name
    !endif
    introduce($name, Info($label, $tag, $note, $shape, $scale, $color, $background))
!endprocedure
