' Mutable state
' ##################################

!if $DST_PUML_ENTITY_NAMES == "dynamic"
    !global $dynamicElementNames = "active"
!else
    !global $dynamicElementNames = "inactive"
!endif


' Element Related State
!global $actorCounter = 0
!global $objectCounter = 0
!global $elementCounter = 0

' Activity Related State
!global $stepCounter = 0

!global $lastNodeConnected = ""
!global $splitNode = ""
!global $currentActivityDirection = ""
