' Logging Utilities
' ##################################

!procedure $debug($message)
    !if LOG_LEVEL == "debug"
        !log [DEBUG] $message
    !endif
!endprocedure

' Entity Creation Utilities
' ##################################

/' Creates a colorized sprite
Params:
    $sprite:   the sprite for the image
    $scale:    the scale for the sprite
    $color:    the color for the sprite '/
!function $pumlSprite($sprite, $scale = 1, $color = "")
    !if $color
        !return "<" + $sprite + "{scale=" + $scale + ",color=" + $color + "}>"
    !else
        !return "<" + $sprite + "{scale=" + $scale + "}>"
    !endif
!endfunction

/' Creates an aliased entity with a colorized sprite, label, and stereotype
Params:
    $type:         the entity type (e.g. component, node, agent, etc.)
    $label:        the label to display under the sprite
    $alias:        the alias to give the entity
    $sprite:       the sprite for the image representing the entity
    $scale:        the scale for the sprite
    $color:        the color for the sprite
    $stereo:       the stereotype, which can define additional styling
    $background:   the background color '/
!procedure $pumlEntity($type, $label, $alias, $sprite = "", $scale = 1, $color = "", $stereo = "", $background = "")
    !if $sprite
$type "$pumlSprite($sprite, $scale, $color)\r##$label" as $alias $stereo $background
    !else
$type "$label" as $alias $stereo $background
    !endif
!endprocedure

' Various Auxiliary Utilities
' ##################################

!function $computeStereotypes($kind, $tag, $all = %true())
    !if $kind
        !if $tag
            !if $all
                !return "<<" + $kind + ":" + $tag + ">><<" + $kind + ">><<" + $tag + ">>"
            !else
                !return "<<" + $kind + ":" + $tag + ">>"
            !endif
        !else
            !return "<<" + $kind + ">>"
        !endif
    !else
        !if $tag
            !return "<<" + $tag + ">>"
        !else
            !return ""
        !endif
    !endif
!endfunction

!function $decideVariableName($context, $tag, $property)
    !if $tag
        !return "$" + $context + "_" + $tag + "_" + $property
    !else
        !return "$" + $context + "_" + $property
    !endif
!endfunction
