@startuml
!startsub setUp
!$Story_Layout = 'left-to-right'

!include ../../../src/domainStoryComposite.puml
!endsub

!startsub above
Boundary(company) {
    introduce(Person(sarah))
}
note top of company : !! above ??
!endsub

!startsub right
Boundary(team) {
    introduce(Person(pete))
}
note right of team : right
!endsub

!startsub below
Boundary(office) {
    introduce(Call(conference))
}
note bottom of office : below ??
!endsub

!startsub left
Boundary(party) {
    introduce(Group(people))
}
note left of party : left
!endsub
@enduml
