@startuml
!startsub setUp
!$Story_Layout = 'left-to-right'

!include ../../../src/domainStoryComposite.puml
!endsub

!startsub default
Boundary(one, $note= default) {
    introduce(Person(Jake))
}
!endsub

!startsub above
Boundary(two, $note=^ !! above) {
    introduce(Person(Simon))
}
!endsub

!startsub right
Boundary(three, $note=> right) {
    introduce(Person(Sloane))
}
!endsub

!startsub below
Boundary(four, $note=v below) {
    introduce(Person(Marry))
}
!endsub

!startsub left
Boundary(five, $note=< left) {
    introduce(Person(Ashley))
}
!endsub

!startsub inverse
Boundary(six, $note=~ inverse) {
    introduce(Person(Sam))
}
!endsub
@enduml
