@startuml
!$Story_Layout = 'left-to-right'

!include ../../../src/domainStoryComposite.puml

Boundary(one, $note= default) {
    Person(Jake)
}

Boundary(two, $note=^ above) {
    Person(Simon)
}

Boundary(three, $note=> right) {
    Person(Sloane)
}

Boundary(four, $note=v below) {
    Person(Marry)
}

Boundary(five, $note=< left) {
    Person(Ashley)
}

Boundary(six, $note=~ inverse) {
    Person(Sam)
}
@enduml
