@startuml
!$Story_Layout = 'left-to-right'

!include ../../../src/domainStoryComposite.puml

introduce(Person(person))

introduce(Info(thing1))
introduce(Info(thing2))
introduce(Info(thing3))

activity(1, person, reads, thing1, $note= default)
activity(2, person, reads, thing2, $note=^ above)
activity(3, person, reads, thing3, $note=> right)
activity(4, person, reads, Info: thing4, $note=v below)
activity(5, person, reads, Info: thing5, $note=< left)
activity(6, person, reads, Info: thing6, $note=~ inverse)
activity(7, person, reads, Document:Book, $note=> right)
@enduml
