@startuml
!$Story_Layout = 'left-to-right'

!include ../../../src/domainStoryComposite.puml

introduce(Person(pete))

note top of pete : above
note right of pete : right
note bottom of pete : below
note left of pete : left

introduce(Email(confirmation, $note= default))
introduce(Info(news, $note=^ above))
introduce(Document(list, $note=> right))
introduce(Folder(documents, $note=v below))
introduce(Call(question, $note=< left))
introduce(Conversation(argument, $note=~ inverse))

introduce(Person(Alice, $note= default))
introduce(Group(Employees, $note=~ inverse))
introduce(System(Boarding, $note=^ above))
@enduml
