@startuml
!$DefaultFontColor = Navy
!$DefaultBackgroundColor = "#EEA"
!$DefaultBorderColor = green
!$DefaultBorderThickness = 3

!$ActorIconColor = LightBlue
!$ActorFontColor = Orange
!$ActorFontStyle = bold
!$ActorBackgroundColor = "#777"
!$ActorBorderColor = yellow
!$ActorBorderThickness = 3

!$BoundaryFontColor = limegreen

!$EmailIconColor = grey

!$StepFontColor = PowderBlue
!$StepBackgroundColor = Darkgrey

!include ../../domainStory.puml

Person(Alice)

System(FOo)

Boundary(Home) {
    Email(spam)
}

Person(Bob, $color=white)
Boundary(Party, $background=yellow/red) {
    Conversation(weather, $color=brown)
}

Boundary(Office, $background=#aee) {
    Email(proposal, $scale=3, $color=#f03000)
}

activity(_, Alice, reads the, spam, _, _, ->)
activity(_, Alice, talks about the, weather, with, Bob)
activity(<_, Bob, writes a, proposal, to, Alice)
@enduml
