@startuml
!$Person_BackgroundColor = red

!$System_Shape = action
!$System_Background = lightgrey

!$Group_FontSize = 30

!$Conversation_IconStyle = "filled"

!$Document_IconStyle = something
!$Document_IconColor = blue

!$Email_IconScale = '1.5'
!$Email_IconColor = grey
!$Email_BackgroundColor = "orange"
!$Email_BorderStyle = "solid"
!$Email_BorderColor = "red"

!$Call_IconName = "&phone"
!$Call_IconScale = "6"
!$Call_IconColor = grey

!$Info_FontStyle = italic
!$Info_FontSize = 20

!$Folder_Shape = database

!include ../../src/domainStoryComposite.puml

Email(confirmation)
Info(news)
Document(list)
Folder(documents)
Call(question)
Conversation(argument)

Person(Alice)
Group(Employees)
System(Boarding)

Boundary(Home) {
    Email(spam)
}

Person(Bob)

Boundary(Party) {
    Conversation(weather)
}

Boundary(Office) {
    Email(proposal)
}

activity(+, Alice, reads the, spam, _, _, ->)
activity(+, Alice, talks about the, weather, with, Bob)
activity(<+, Bob, writes a, proposal, to, Alice)
@enduml
