@startuml
!theme sunlust

!$Story_Layout = 'top-to-bottom'
!$Step_FontColor = yellow
!$Step_BackgroundColor = darkgrey

!include ../../src/domainStoryComposite.puml

Boundary(Party) {
    Person(Alice)
    Conversation(weather)
    Person(Bob)
}

activity(1, Alice, talks about the, weather, with, Bob)
@enduml
