@startuml
!theme sunlust

!$StoryLayout = 'top-to-bottom'
!$StepFontColor = yellow
!$StepBackgroundColor = darkgrey

!include ../../domainStory.puml

Boundary(Party) {
    Person(Alice)
    Conversation(weather)
    Person(Bob)
}

activity(1, Alice, talks about the, weather, with, Bob)
@enduml
