@startuml
!$DST_PUML_ENTITY_NAMES = "dynamic"

!include ../../../src/domainStoryComposite.puml

introduce(Person(Pete))

!assert $actorCounter == 1
!assert Pete == "actor1"
!assert $lastCreatedActor == "actor1"
!assert $lastCreatedElement == "actor1"

introduce(Maria, Person(Maria))

!assert $actorCounter == 2
!assert Maria == "actor2"
!assert $lastCreatedActor == "actor2"
!assert $lastCreatedElement == "actor2"

introduce(Sarah, Person(Smart Sarah))

!assert $actorCounter == 3
!assert Sarah == "actor3"
!assert $lastCreatedActor == "actor3"
!assert $lastCreatedElement == "actor3"

introduce(Frida, Person(Funny Frida, funny))

!assert $actorCounter == 4
!assert Frida == "actor4"
!assert $lastCreatedActor == "actor4"
!assert $lastCreatedElement == "actor4"

introduce(Hannah, Person(Happy Hannah, happy, real happy))

!assert $actorCounter == 5
!assert Hannah == "actor5"
!assert $lastCreatedActor == "actor5"
!assert $lastCreatedElement == "actor5"

introduce(Max, Person(Mindful Max, mindful, thinks a lot, cloud))

!assert $actorCounter == 6
!assert Max == "actor6"
!assert $lastCreatedActor == "actor6"
!assert $lastCreatedElement == "actor6"

introduce(Noah, Person(Noble Noah, noble, shows high moral qualities, cloud, 2))

!assert $actorCounter == 7
!assert Noah == "actor7"
!assert $lastCreatedActor == "actor7"
!assert $lastCreatedElement == "actor7"

introduce(Olivia, Person(Orderly Olivia, orderly, is organized, folder, 2, darkblue))

!assert $actorCounter == 8
!assert Olivia == "actor8"
!assert $lastCreatedActor == "actor8"
!assert $lastCreatedElement == "actor8"

introduce(Quentin, Person(Questioning Quentin, questioning, doubtful, database, 2, red, grey))

!assert $actorCounter == 9
!assert Quentin == "actor9"
!assert $lastCreatedActor == "actor9"
!assert $lastCreatedElement == "actor9"
@enduml
